#!/usr/bin/env npx ts-node --esm
/**
 * Usage: npx ts-node --esm scripts/copy-to.ts <destination>
 *   e.g. npx ts-node --esm scripts/copy-to.ts ~/Desktop/ultrawork-copy
 *
 * Copies the ultrawork directory to <destination>, skipping:
 *   - node_modules
 *   - src-tauri/target
 *   - dist
 *   - .tsbuildinfo files
 *   - bun.lockb (will be regenerated by bun install)
 */

import * as fs from "node:fs"
import * as path from "node:path"
import * as os from "node:os"

const EXCLUDE_DIRS = new Set(["node_modules", "target", "dist", ".git"])
const EXCLUDE_FILES = new Set(["bun.lockb"])
const EXCLUDE_EXTENSIONS = new Set([".tsbuildinfo"])

function expandTilde(p: string): string {
  if (p.startsWith("~/") || p === "~") {
    return path.join(os.homedir(), p.slice(1))
  }
  return p
}

function copyDir(src: string, dest: string, depth = 0): void {
  fs.mkdirSync(dest, { recursive: true })

  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const name = entry.name
    const srcPath = path.join(src, name)
    const destPath = path.join(dest, name)

    if (entry.isDirectory()) {
      // Skip excluded dirs — but only skip "target" inside src-tauri
      if (EXCLUDE_DIRS.has(name)) {
        if (name !== "target" || src.endsWith("src-tauri")) {
          console.log(`  skip  ${path.relative(ROOT, srcPath)}/`)
          continue
        }
      }
      copyDir(srcPath, destPath, depth + 1)
    } else if (entry.isSymbolicLink()) {
      // Preserve symlinks (used in app/public for asset references)
      const linkTarget = fs.readlinkSync(srcPath)
      if (fs.existsSync(destPath)) fs.unlinkSync(destPath)
      fs.symlinkSync(linkTarget, destPath)
    } else {
      if (EXCLUDE_FILES.has(name)) continue
      if (EXCLUDE_EXTENSIONS.has(path.extname(name))) continue
      fs.copyFileSync(srcPath, destPath)
    }
  }
}

const ROOT = path.resolve(import.meta.dirname, "..")

const dest = process.argv[2]
if (!dest) {
  console.error("Usage: npx ts-node --esm scripts/copy-to.ts <destination>")
  process.exit(1)
}

const destAbs = path.resolve(expandTilde(dest))

if (fs.existsSync(destAbs)) {
  console.error(`Error: destination already exists: ${destAbs}`)
  console.error("Remove it first or choose a different path.")
  process.exit(1)
}

console.log(`Copying ultrawork → ${destAbs}`)
console.log(`Excluding: node_modules, src-tauri/target, dist, .tsbuildinfo\n`)

copyDir(ROOT, destAbs)

console.log(`\nDone. Now run:\n  cd ${destAbs}\n  bun install`)
